/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x8.h"
#include "STM32_I2C.h"
#include "I2C_Slave_EEPROM.h"

void Clock_Init(void)
{
	RCC_GPIOA_CLK_DIS();
	RCC_GPIOB_CLK_DIS();
	RCC_AFIO_CLK_EN();
	RCC_I2C1_CLK_EN();
}


int main(void)
{
    Clock_Init();

	//Test Case 1
    uint8_t buff1[] = {1, 2, 3, 4, 5, 6, 7};
	uint8_t buff2[7] = {0};

	HAL_EEPROM_Init();
	HAL_EEPROM_Write_Nbytes(0xAF, buff1, 7);
	HAL_EEPROM_Read_Nbytes(0xAF, buff2, 7);


	//Test Case 2
	buff1[0] = 10;
	buff1[1] = 11;
	buff1[2] = 12;
	buff1[3] = 13;

	HAL_EEPROM_Write_Nbytes(0xFFF, buff1, 4);
	HAL_EEPROM_Read_Nbytes(0xFFF, buff2, 4);

	while(1)
	{

	}

}
